=== ipallares/shopping_cart_api/src/JsonSchema/cart-api-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://example.com/example.json",
    "type": "object",
    "title": "Cart API Schema",
    "required": [
        "cartProducts"
    ],
    "properties": {
        "id": {
            "$id": "#/properties/id",
            "type": "string",
            "title": "The id schema"
        },
        "creationDate": {
            "$id": "#/properties/creationDate",
            "type": "string"
        },
        "lastModified": {
            "$id": "#/properties/lastModified",
            "type": "string"
        },
        "cartProducts": {
            "$id": "#/properties/cartProducts",
            "type": "array",
            "additionalItems": false,
            "items": {
                "$id": "#/properties/cartProducts/items",
                "anyOf": [
                    {
                        "$id": "#/properties/cartProducts/items/anyOf/0",
                        "type": "object",
                        "required": [
                            "quantity",
                            "productName",
                            "productPrice",
                            "productStock",
                            "productId",
                            "cartProductPrice"
                        ],
                        "properties": {
                            "id": {
                                "$id": "#/properties/cartProducts/items/anyOf/0/properties/id",
                                "type": "string"
                            },
                            "quantity": {
                                "$id": "#/properties/cartProducts/items/anyOf/0/properties/quantity",
                                "type": "integer"
                            },
                            "productName": {
                                "$id": "#/properties/cartProducts/items/anyOf/0/properties/productName",
                                "type": "string"
                            },
                            "productPrice": {
                                "$id": "#/properties/cartProducts/items/anyOf/0/properties/productPrice",
                                "type": "integer"
                            },
                            "productStock": {
                                "$id": "#/properties/cartProducts/items/anyOf/0/properties/productStock",
                                "type": "integer"
                            },
                            "productId": {
                                "$id": "#/properties/cartProducts/items/anyOf/0/properties/productId",
                                "type": "string"
                            },
                            "cartProductPrice": {
                                "$id": "#/properties/cartProducts/items/anyOf/0/properties/cartProductPrice",
                                "type": "integer"
                            }
                        },
                        "additionalProperties": false
                    }
                ]
            }
        }
    },
    "additionalProperties": false
}

=== ipallares/shopping_cart_api/tests/Logic/Validator/json-examples/valid-cart-api-example-v1.json
{
    "id": "B30EC520-659A-4281-A5F4-2226DF88EC94",
    "creationDate": "27.03.2021 22:12:05",
    "lastModified": "27.03.2021 22:12:05",
    "cartProducts": [
        {
            "id": "237705C4-CE7A-4D0B-BEE4-0EAA7F969241",
            "quantity": 3,
            "productName": "Product1",
            "productPrice": 1199,
            "productStock": 200,
            "productId": "0AF60D38-1916-4142-9CCE-1DDFBC4EC178",
            "cartProductPrice": 1199
        },
        {
            "id": "B30EC520-659A-4281-A5F4-2226DF88EC94",
            "quantity": 1,
            "productName": "Product2",
            "productPrice": 2499,
            "productStock": 10,
            "productId": "CCECBB9E-7F97-48B0-B553-D221671EC131",
            "cartProductPrice": 2499
        },
        {
            "id": "B30EC520-659A-4281-A5F4-2226DF88EC94",
            "quantity": 1,
            "productName": "Product2",
            "productPrice": 2499,
            "productStock": 10,
            "productId": "CCECBB9E-7F97-48B0-B553-D221671EC131",
            "cartProductPrice": 2499
        }
    ]
}
